name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        function Invoke-Environment {
            param
            (
                # Any cmd shell command, normally a configuration batch file.
                [Parameter(Mandatory=$true)]
                [string] $Command
            )

            $Command = "`"" + $Command + "`""
            cmd /c "$Command > nul 2>&1 && set" | . { process {
                if ($_ -match '^([^=]+)=(.*)') {
                    [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
                }
            }}
        }
        cd libdjvu
        Invoke-Environment "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        & "nmake.exe X64=1"
        cd ..
        & nmake.exe "X64=1"
        dir
